// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vyzio.Infrastructure.Persistence;

#nullable disable

namespace Vyzio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VyzioDbContext))]
    [Migration("20260514174000_AddNotificationSchedule")]
    partial class AddNotificationSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Vyzio.Core.Entities.Camera", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectionPreset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("detection_preset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("FrigateCameraName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("frigate_camera_name");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastReachabilityCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_reachability_check_at");

                    b.Property<DateTime?>("LastSuccessfulFrameAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_successful_frame_at");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StreamPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("stream_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("ValidationState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_state");

                    b.Property<string>("VendorFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor_family");

                    b.HasKey("Id")
                        .HasName("pk_cameras");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("idx_cameras_display_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_cameras_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_cameras_status");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.DetectionEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("camera");

                    b.Property<float?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("FrigateEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("frigate_event_id");

                    b.Property<bool>("HasClip")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_clip");

                    b.Property<bool>("HasSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_snapshot");

                    b.Property<string>("Identity")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("identity");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProfileId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_observed_events");

                    b.HasIndex("FrigateEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_events_frigate_event_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_events_occurred");

                    b.HasIndex("ProfileId", "OccurredAt")
                        .HasDatabaseName("idx_events_profile");

                    b.ToTable("observed_events", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.NotificationChannelConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveFromHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_from_hour");

                    b.Property<int?>("ActiveToHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_to_hour");

                    b.Property<string>("AllowedLabelsJson")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_labels_json");

                    b.Property<string>("BotToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("bot_token");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("ChatId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("chat_id");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("configured_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LastTestError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_test_error");

                    b.Property<string>("LastTestStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_test_status");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_tested_at");

                    b.Property<float>("MinimumConfidence")
                        .HasColumnType("REAL")
                        .HasColumnName("minimum_confidence");

                    b.HasKey("Id")
                        .HasName("pk_notification_channel_configs");

                    b.ToTable("notification_channel_configs", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlertMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_mode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.DetectionEvent", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Profile", "Profile")
                        .WithMany("DetectionEvents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_observed_events_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Profile", b =>
                {
                    b.Navigation("DetectionEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
