// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vyzio.Infrastructure.Persistence;

#nullable disable

namespace Vyzio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VyzioDbContext))]
    [Migration("20260509195119_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Vyzio.Core.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlertMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_mode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ObservedEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("camera");

                    b.Property<float?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("FrigateEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("frigate_event_id");

                    b.Property<bool>("HasClip")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_clip");

                    b.Property<bool>("HasSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_snapshot");

                    b.Property<string>("Identity")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("identity");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProfileId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_observed_events");

                    b.HasIndex("FrigateEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_events_frigate_event_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_events_occurred");

                    b.HasIndex("ProfileId", "OccurredAt")
                        .HasDatabaseName("idx_events_profile");

                    b.ToTable("observed_events", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ObservedEvent", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Profile", "Profile")
                        .WithMany("ObservedEvents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_observed_events_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Profile", b =>
                {
                    b.Navigation("ObservedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
