// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vyzio.Infrastructure.Persistence;

#nullable disable

namespace Vyzio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VyzioDbContext))]
    [Migration("20260831212006_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Vyzio.Core.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_changed_at");

                    b.Property<DateTime?>("PasswordForgottenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_forgotten_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Camera", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ContinuousDaysOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("continuous_days_override");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectStreamId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("detect_stream_id");

                    b.Property<string>("DetectionLabelsJson")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("detection_labels_json");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int?>("EventClipDaysOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_clip_days_override");

                    b.Property<string>("FrigateCameraName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("frigate_camera_name");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastReachabilityCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_reachability_check_at");

                    b.Property<DateTime?>("LastSuccessfulFrameAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_successful_frame_at");

                    b.Property<int?>("MotionDaysOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motion_days_override");

                    b.Property<int>("MotionSensitivity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motion_sensitivity");

                    b.Property<bool>("MotionSensitivityPinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motion_sensitivity_pinned");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<bool>("PrivacyModeActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privacy_mode_active");

                    b.Property<string>("PrivacyModeSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_mode_source");

                    b.Property<string>("PrivacyStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("privacy_strategy");

                    b.Property<bool>("PrivacyVendorCut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("privacy_vendor_cut");

                    b.Property<bool>("PtzSupported")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ptz_supported");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StreamProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stream_protocol");

                    b.Property<string>("SupportedProtocolsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("supported_protocols_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("ValidationState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_state");

                    b.Property<string>("VendorFamily")
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor_family");

                    b.HasKey("Id")
                        .HasName("pk_cameras");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_cameras_device");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("idx_cameras_display_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_cameras_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_cameras_status");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CameraCapabilityBinding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capability");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<bool>("ManuallyConfigured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manually_configured");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verified");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_camera_capability_bindings");

                    b.HasIndex("CameraId", "Capability")
                        .IsUnique()
                        .HasDatabaseName("ux_capability_bindings_camera_capability");

                    b.ToTable("camera_capability_bindings", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CameraPrivacySchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("days_of_week");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_camera_privacy_schedules");

                    b.HasIndex("CameraId", "Enabled")
                        .HasDatabaseName("idx_privacy_schedules_camera");

                    b.ToTable("camera_privacy_schedules", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CameraStream", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("Fps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fps");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_camera_streams");

                    b.HasIndex("CameraId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_camera_streams_camera_ordinal");

                    b.ToTable("camera_streams", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ChannelPairing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("CodeExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("code_expires_at");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("PairedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("paired_at");

                    b.Property<string>("PairingCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("pairing_code");

                    b.HasKey("Id")
                        .HasName("pk_channel_pairings");

                    b.HasIndex("Channel")
                        .IsUnique()
                        .HasDatabaseName("idx_channel_pairings_channel");

                    b.ToTable("channel_pairings", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CommandJournal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_command_journal");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_command_journal_received");

                    b.HasIndex("Channel", "ConversationId", "ReceivedAt")
                        .HasDatabaseName("idx_command_journal_origin");

                    b.ToTable("command_journal", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("camera");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("FrigateEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("frigate_event_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("FrigateEventId", "Channel")
                        .HasDatabaseName("idx_notifications_event");

                    b.HasIndex("Channel", "Camera", "Label", "SentAt")
                        .HasDatabaseName("idx_notifications_cooldown");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.NotificationChannelConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveFromHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_from_hour");

                    b.Property<int?>("ActiveToHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_to_hour");

                    b.Property<string>("AllowedLabelsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_labels_json");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("configured_at");

                    b.Property<int?>("CooldownMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cooldown_minutes");

                    b.Property<string>("CredentialsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("credentials_json");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LastTestError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_test_error");

                    b.Property<string>("LastTestOutcome")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_test_outcome");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_tested_at");

                    b.Property<string>("MediaMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("media_mode");

                    b.Property<string>("MessageFieldsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_fields_json");

                    b.Property<float>("MinimumConfidence")
                        .HasColumnType("REAL")
                        .HasColumnName("minimum_confidence");

                    b.HasKey("Id")
                        .HasName("pk_notification_channel_configs");

                    b.HasIndex("Channel")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_channel");

                    b.ToTable("notification_channel_configs", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlertMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_mode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ProfileCameraLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_profile_camera_links");

                    b.HasIndex("CameraId", "Enabled")
                        .HasDatabaseName("idx_pcl_camera");

                    b.HasIndex("ProfileId", "CameraId")
                        .IsUnique()
                        .HasDatabaseName("ux_pcl_profile_camera");

                    b.HasIndex("ProfileId", "Enabled")
                        .HasDatabaseName("idx_pcl_profile");

                    b.ToTable("profile_camera_links", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ProfilePhoto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<bool>("FrigateSynced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frigate_synced");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_id");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at");

                    b.HasKey("Id")
                        .HasName("pk_profile_photos");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("idx_photos_profile");

                    b.ToTable("profile_photos", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.PtzPreset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<bool>("Native")
                        .HasColumnType("INTEGER")
                        .HasColumnName("native");

                    b.Property<string>("NativeToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("native_token");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_id");

                    b.Property<int?>("StepsX")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steps_x");

                    b.Property<int?>("StepsY")
                        .HasColumnType("INTEGER")
                        .HasColumnName("steps_y");

                    b.HasKey("Id")
                        .HasName("pk_ptz_presets");

                    b.HasIndex("CameraId", "PresetId")
                        .IsUnique()
                        .HasDatabaseName("ux_ptz_presets_camera_preset");

                    b.ToTable("ptz_presets", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.RecordingSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ContinuousDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("continuous_days");

                    b.Property<int>("EventClipDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_clip_days");

                    b.Property<int>("MotionDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motion_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recording_settings");

                    b.ToTable("recording_settings", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("device");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_sessions_account");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_sessions_token");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CameraCapabilityBinding", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camera_capability_bindings_cameras_camera_id");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CameraPrivacySchedule", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camera_privacy_schedules_cameras_camera_id");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.CameraStream", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Camera", "Camera")
                        .WithMany("Streams")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camera_streams_cameras_camera_id");

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ProfileCameraLink", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_camera_links_cameras_camera_id");

                    b.HasOne("Vyzio.Core.Entities.Profile", "Profile")
                        .WithMany("CameraLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_camera_links_profiles_profile_id");

                    b.Navigation("Camera");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.ProfilePhoto", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Profile", "Profile")
                        .WithMany("Photos")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_photos_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Session", b =>
                {
                    b.HasOne("Vyzio.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_accounts_account_id");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Camera", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("Vyzio.Core.Entities.Profile", b =>
                {
                    b.Navigation("CameraLinks");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
