mqtt:
  host: mqtt
  port: 1883
database:
  path: /media/frigate/frigate.db
detectors:
  cpu1:
    type: cpu
cameras:
  camera_mock_docker:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://mediamtx:8554/test-camera
        roles:
        - detect
    detect:
      enabled: true
      fps: 5
